### ISSUE TITLE
Enlaces rotos en README.md de Pol. IA

### ISSUE THREAD

**Issue by ngeorger** [MinCiencia/Politicas#1]
Estimados:

Primero que tiodo, felicitar e incentivar lo que están haciendo en el Ministerio, y más aún que estén ttrabajando con herramientas Git. Los sigo hace un tiempo y me alegra ver sus commits iniciales, de esta forma será un real ministerio con la nuesva Constitución.
Éste issue, de csarácter más lúdico, es pqra informar que el link 
 en [Politicas/RREADME.md](https://github.com/MinCiencia/Politicas/tree/main/Politica_Inteligencia_Artificial) está roto, arrojando un 404.

Felicitaciones y muchas gracias.

**Comment by MinCiencia** [comment]
Muchas gracias,

Nos parece que está corregido ahora.
